# Generated by Django 3.2.7 on 2021-09-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='stat',
            field=models.BooleanField(default=False),
        ),
    ]
